create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text not null default '',
  windows_version text not null default '',
  ram text not null default '',
  app_version text not null default '',
  dataset_type text not null default '',
  sample_size text not null default '',
  num_constructs text not null default '',
  num_indicators text not null default '',
  features_tested text[] not null default '{}',
  draw_mode jsonb not null default '{}',
  navigation jsonb not null default '{}',
  analysis jsonb not null default '{}',
  tam jsonb not null default '{}',
  overall jsonb not null default '{}',
  screenshot_url text not null default '',
  privacy_policy_version text not null default '',
  privacy_accepted_at timestamptz,
  source_page text not null default '',
  source_title text not null default '',
  ip_address text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_feedback_created_at_desc on public.feedback (created_at desc);
create index if not exists idx_feedback_email on public.feedback (email);
