create schema if not exists public;

create table if not exists public.signups (
  id bigint generated by default as identity primary key,
  token text not null unique,
  name text not null,
  email text not null unique,
  institution text not null default '',
  country text not null default '',
  role text not null default '',
  edition text not null,
  source_page text not null default '',
  source_title text not null default '',
  ip_address text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  beta_visits integer not null default 0,
  last_beta_visit_at timestamptz,
  email_status text not null default 'pending',
  email_error text not null default '',
  email_sent_at timestamptz,
  constraint signups_email_status_check check (email_status in ('pending', 'sent', 'failed'))
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  country text not null default '',
  message text not null default '',
  amount text not null default '',
  ip_address text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null default '',
  body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint comments_body_length_check check (char_length(body) between 1 and 280),
  constraint comments_name_length_check check (char_length(name) <= 60)
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text not null default '',
  windows_version text not null default '',
  ram text not null default '',
  app_version text not null default '',
  dataset_type text not null default '',
  sample_size text not null default '',
  num_constructs text not null default '',
  num_indicators text not null default '',
  features_tested text[] not null default '{}',
  draw_mode jsonb not null default '{}',
  navigation jsonb not null default '{}',
  analysis jsonb not null default '{}',
  tam jsonb not null default '{}',
  overall jsonb not null default '{}',
  screenshot_url text not null default '',
  privacy_policy_version text not null default '',
  privacy_accepted_at timestamptz,
  source_page text not null default '',
  source_title text not null default '',
  ip_address text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_signups_created_at_desc on public.signups (created_at desc);
create index if not exists idx_signups_updated_at_desc on public.signups (updated_at desc);
create index if not exists idx_signups_edition on public.signups (edition);
create index if not exists idx_signups_email_status on public.signups (email_status);
create index if not exists idx_signups_last_beta_visit_at on public.signups (last_beta_visit_at desc);
create index if not exists idx_donations_created_at_desc on public.donations (created_at desc);
create index if not exists idx_donations_email on public.donations (email);
create index if not exists idx_comments_created_at_desc on public.comments (created_at desc);
create index if not exists idx_feedback_created_at_desc on public.feedback (created_at desc);
create index if not exists idx_feedback_email on public.feedback (email);
