-- General feedback submissions for metis public website.
-- Use this when the backend is ready to store submit-feedback.html separately
-- from the longer testing feedback form at feedback.html.

CREATE TABLE IF NOT EXISTS general_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  institution TEXT NOT NULL DEFAULT '',
  used_for TEXT NOT NULL DEFAULT '',
  easy TEXT NOT NULL DEFAULT '',
  confusing TEXT NOT NULL DEFAULT '',
  improve TEXT NOT NULL DEFAULT '',
  feature_next TEXT NOT NULL DEFAULT '',
  overall_rating INTEGER NOT NULL CHECK (overall_rating BETWEEN 1 AND 5),
  quote_permission TEXT NOT NULL DEFAULT 'no' CHECK (quote_permission IN ('yes', 'no')),
  contact_permission TEXT NOT NULL DEFAULT 'no' CHECK (contact_permission IN ('yes', 'no')),
  privacy_policy_version TEXT NOT NULL DEFAULT '',
  privacy_accepted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  source_page TEXT NOT NULL DEFAULT '',
  source_title TEXT NOT NULL DEFAULT 'General feedback',
  ip_address TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_general_feedback_created_at
  ON general_feedback(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_general_feedback_quote_permission
  ON general_feedback(quote_permission);

CREATE INDEX IF NOT EXISTS idx_general_feedback_contact_permission
  ON general_feedback(contact_permission);

-- Admin dashboard list query.
SELECT
  id,
  name,
  email,
  role,
  country,
  institution,
  used_for,
  easy,
  confusing,
  improve,
  feature_next,
  overall_rating,
  quote_permission,
  contact_permission,
  created_at
FROM general_feedback
ORDER BY created_at DESC
LIMIT 250;
