-- ─────────────────────────────────────────────────────────────────────────
-- comments-migration.sql
-- Run this once in Supabase Studio (SQL editor) to add the wall feature.
-- Safe to run multiple times — uses IF NOT EXISTS guards.
--
-- After running this, run comments-seed.sql to insert the 4 starter notes.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.comments (
  id           bigint generated by default as identity primary key,
  name         text not null default '',
  body         text not null,
  created_at   timestamptz not null default timezone('utc', now()),
  constraint comments_body_length_check check (char_length(body) between 1 and 280),
  constraint comments_name_length_check check (char_length(name) <= 60)
);

alter table public.comments drop column if exists ip_address;
alter table public.comments drop column if exists user_agent;

create index if not exists idx_comments_created_at_desc
  on public.comments (created_at desc);

-- Row level security:
--   Reads happen through the backend (service-role key) and are returned via
--   the /api/comments endpoint, but enabling RLS here is good hygiene in case
--   anyone ever tries the anon key against this table.
alter table public.comments enable row level security;

-- No public read or write policies — only the service role (backend) can
-- read/write. Drop existing policies (idempotent) then leave the table
-- locked down to anon/auth roles.
drop policy if exists "comments_no_anon_select" on public.comments;
drop policy if exists "comments_no_anon_insert" on public.comments;

-- (Optional) If you ever want to expose read access directly to the anon
-- key (so the browser can fetch comments without going through the backend),
-- uncomment the policy below. Recommended: keep it commented and use the
-- /api/comments endpoint, which is rate-limited and cached.
--
-- create policy "comments_anon_select"
--   on public.comments for select
--   to anon
--   using (true);
